### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by rs0h** [LostMyCode/javascript-deobfuscator#34]
Request to
https://us-central1-deobfuscator.cloudfunctions.net/api/request
gives me error 500. 
Script is about 1Mb size.

Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:61:7)

**Comment by Havock94** [comment]
Same for me with a bigger script, around 6Mb.

Any particular reason it happens?
Thank you
